# Generated by Django 4.1 on 2022-08-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('direcction', models.CharField(max_length=75)),
                ('department', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=75)),
            ],
        ),
    ]
